export const availablePlans = [
  {
    id: 'gratis',
    name: 'FREE',
    price: 0,
    currency: 'USD',
    billing_period: 'monthly' as const,
    features: {
      max_products: 10,
      max_categories: 5,
      analytics: false,
      custom_domain: false,
      priority_support: false,
      advanced_customization: false,
    },
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 15,
    currency: 'USD',
    billing_period: 'monthly' as const,
    features: {
      max_products: 50,
      max_categories: 15,
      analytics: true,
      custom_domain: false,
      priority_support: false,
      advanced_customization: true,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 35,
    currency: 'USD',
    billing_period: 'monthly' as const,
    popular: true,
    features: {
      max_products: 200,
      max_categories: 50,
      analytics: true,
      custom_domain: true,
      priority_support: true,
      advanced_customization: true,
    },
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 80,
    currency: 'USD',
    billing_period: 'monthly' as const,
    features: {
      max_products: 999999,
      max_categories: 999999,
      analytics: true,
      custom_domain: true,
      priority_support: true,
      advanced_customization: true,
    },
  },
];
