export const availablePlans = [
  {
    id: 'free',
    name: 'FREE',
    monthlyPrice: 0,
    annualPrice: 0,
    currency: 'COP',
    popular: false,
    features: {
      max_products: 5,
      max_categories: 5,
      analytics: false,
      custom_domain: false,
      priority_support: false,
      advanced_customization: false,
      ai_assistant: false,
    },
  },
  {
    id: 'basic',
    name: 'Basic',
    monthlyPrice: 49900,
    annualPrice: 509000,
    currency: 'COP',
    popular: false,
    features: {
      max_products: 25,
      max_categories: 15,
      analytics: true,
      custom_domain: false,
      priority_support: false,
      advanced_customization: true,
      ai_assistant: false,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    monthlyPrice: 99900,
    annualPrice: 1019000,
    currency: 'COP',
    popular: true,
    features: {
      max_products: 100,
      max_categories: 25,
      analytics: true,
      custom_domain: true,
      priority_support: true,
      advanced_customization: true,
      ai_assistant: false,
    },
  },
  {
    id: 'business',
    name: 'Business',
    monthlyPrice: 199900,
    annualPrice: 2039000,
    currency: 'COP',
    popular: false,
    features: {
      max_products: 200,
      max_categories: 50,
      analytics: true,
      custom_domain: true,
      priority_support: true,
      advanced_customization: true,
      ai_assistant: true,
    },
  },
];
